name: CI

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build test
      env:
        CI: true
    - name: Check for uncommitted changes and configure git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add -N .
        if git diff --stat HEAD | grep -P . ; then
          echo "uncommitted changes detected, please npm run all and commit";
          exit 1;
        fi
        cat <<- EOF > $HOME/.netrc
          machine github.com
          login $GITHUB_ACTOR
          password $GITHUB_TOKEN
          machine api.github.com
          login $GITHUB_ACTOR
          password $GITHUB_TOKEN
        EOF
        chmod 600 $HOME/.netrc
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
    - name: Publish site
      run: npm run deploy
